## Proyecto 1: Análisis de señales ECG y detección de arritmias 
## Proyecto 2026-02 


## Presentado por:

# Esteban Garcia Otalvaro
# Fabian Andres Posso

In [12]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

2. Cargar el archivo Diagnostics.xlsx y realizar un análisis estadístico general de los datos. Desde la información en la base de datos resolver las siguientes preguntas

In [13]:
ruta_diagnostics = r"C:\Users\LENOVO\OneDrive - Universidad de Antioquia\Escritorio\BIOSEÑALES Y SISTEMAS\Laboratorio\ECGDataDenoised\Diagnostics.xlsx"
df = pd.read_excel(ruta_diagnostics)
# Observación preliminar de las variables y estructura del dataset
df.describe()

,PatientAge,VentricularRate,AtrialRate,QRSDuration,QTInterval,QTCorrected,RAxis,TAxis,QRSCount,QOnset,QOffset,TOffset
count,10646.000000,10646.000000,10646.00000,10646.000000,10646.000000,10646.000000,10646.000000,10646.000000,10646.000000,10646.000000,10646.000000,10646.000000
mean,59.186831,84.136107,92.57787,90.989292,384.150855,434.154048,39.620609,44.637704,13.839470,219.260567,264.755213,411.335995
std,18.030019,34.455349,60.09394,17.479540,59.226289,39.354182,41.212648,57.478092,5.676339,6.410413,8.362120,29.777404
min,4.000000,34.000000,0.00000,18.000000,114.000000,219.000000,-89.000000,-89.000000,5.000000,159.000000,249.000000,281.000000
25%,49.000000,57.000000,57.00000,80.000000,344.000000,408.000000,14.000000,19.000000,9.000000,216.000000,259.000000,392.000000
50%,62.000000,73.000000,72.00000,88.000000,390.000000,430.000000,46.000000,42.000000,12.000000,219.000000,264.000000,414.000000
75%,72.000000,104.000000,106.00000,98.000000,426.000000,456.000000,68.000000,62.000000,17.000000,224.000000,268.000000,432.000000
max,98.000000,263.000000,535.00000,256.000000,736.000000,760.000000,270.000000,270.000000,40.000000,240.000000,331.000000,582.000000

In [14]:
df.groupby(by=["Rhythm"]).describe()

       PatientAge                                                       \
            count       mean        std   min    25%   50%   75%   max
Rhythm
AF          445.0  71.065169  13.497673  21.0  63.00  72.0  81.0  97.0
AFIB       1780.0  73.359551  11.137343  30.0  67.00  75.0  82.0  98.0
AT          121.0  65.719008  19.300787   8.0  60.00  71.0  77.0  94.0
AVNRT        16.0  57.875000  17.335417  27.0  51.00  59.0  66.0  84.0
AVRT          8.0  57.500000  16.835337  25.0  47.75  62.5  67.0  77.0
SA          399.0  34.746867  23.029446   4.0  14.50  29.0  52.5  93.0
SAAWR         7.0  51.142857  31.829905  15.0  22.50  49.0  81.0  87.0
SB         3889.0  58.339676  13.952579  10.0  50.00  60.0  68.0  98.0
SR         1826.0  54.352136  16.331977   4.0  44.00  55.0  66.0  95.0
ST         1568.0  54.565051  21.060029   4.0  40.00  57.0  70.0  96.0
SVT         587.0  55.623509  18.527343   4.0  42.00  56.0  69.0  96.0

       VentricularRate              ... QOffset        TOffset              \
                 count        mean  ...     75%    max   count        mean
Rhythm                              ...
AF               445.0  114.577528  ...  272.00  314.0   445.0  392.907865
AFIB            1780.0   95.489326  ...  269.00  311.0  1780.0  402.439888
AT               121.0  116.438017  ...  267.00  294.0   121.0  387.388430
AVNRT             16.0  172.250000  ...  271.00  316.0    16.0  359.062500
AVRT               8.0  171.000000  ...  266.75  274.0     8.0  358.125000
SA               399.0   72.922306  ...  266.50  299.0   399.0  411.834586
SAAWR              7.0   64.428571  ...  266.00  274.0     7.0  423.428571
SB              3889.0   55.022885  ...  269.00  314.0  3889.0  435.605554
SR              1826.0   75.748083  ...  267.00  311.0  1826.0  413.105148
ST              1568.0  112.157526  ...  266.00  303.0  1568.0  386.538265
SVT              587.0  168.367973  ...  271.00  331.0   587.0  358.831346


              std    min    25%    50%     75%    max
Rhythm
AF      34.783087  302.0  369.0  389.0  412.00  537.0
AFIB    26.553652  307.0  385.0  403.0  420.00  562.0
AT      25.048743  323.0  372.0  387.0  403.00  490.0
AVNRT   10.009787  334.0  355.5  359.5  363.25  381.0
AVRT    26.351674  318.0  338.0  364.0  378.25  390.0
SA      15.496724  376.0  400.5  411.0  421.00  466.0
SAAWR   15.576233  406.0  414.0  421.0  428.00  453.0
SB      17.177428  385.0  424.0  434.0  445.00  582.0
SR      14.925198  370.0  403.0  413.0  423.00  494.0
ST      15.636704  328.0  377.0  387.0  395.00  559.0
SVT     19.553825  281.0  347.0  359.0  371.00  475.0

[11 rows x 96 columns]